version: '3.5'

services:
  gleague:
    command: ["bash", "./wait-for-postgres.sh", "python wsgi.py"]
    volumes:
      - ./gleague/gleague:/gleague
      - ./gleague/alembic:/alembic
      - ./gleague/tests:/tests
      - ./gleague/cli.py:/cli.py
      - ./gleague/wsgi.py:/wsgi.py
    ports:
      - 127.0.0.1:${GLEAGUE_PORT}:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - DEBUG=1
  postgres:
    volumes:
      - db-data:/var/lib/postgresql/data
  dem2json:
    volumes:
      - ./dem2json/src/dem2json:/src/dem2json
    ports:
      - 5222:5222

volumes:
  db-data:
