version: '3.5'
services:
  gleague:
    image: nuqlya/gleague-core:latest
    volumes:
      - ./wait-for-postgres.sh:/wait-for-postgres.sh
    env_file:
      - .env
    environment:
      - STEAM_API_KEY=${STEAM_API_KEY}
    depends_on:
      - postgres
      - dem2json
      - ssdb
  dem2json:
    image: nuqlya/gleague-dem2json:latest
    command: ["/dem2json"]
    ports:
      - 5222
  postgres:
    image: postgres:9.3
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  ssdb:
    image: leobuskin/ssdb-docker
