version: '3'
services:
  gleague:
    command: ["bash", "./wait-for-postgres.sh", "python wsgi.py"]
    volumes:
      - ./gleague/gleague:/gleague
      - gleague-bower:/gleague/frontend/static/lib/bower_components
      - ./gleague/alembic:/alembic
      - ./gleague/tests:/tests
      - ./gleague/cli.py:/cli.py
      - ./gleague/wsgi.py:/wsgi.py
    ports:
      - ${GLEAGUE_PORT}:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - DEBUG=1
    env_file:
      - .env
  postgres:
    volumes:
      - db-data:/var/lib/postgresql/data
  dem2json:
    volumes:
      - ./dem2json/src/dem2json:/src/dem2json

volumes:
  db-data:
  gleague-bower:
