version: '3.5'
services:
  gleague:
    command: ["bash", "./wait-for-postgres.sh", "py.test ./tests/*"]
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://gleague:1@postgres/gleague-test
  postgres:
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=gleague
      - POSTGRES_DB=gleague-test
